version: 2

project_name: auraspeed

builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w
      - -X 'auraspeed/cmd/root.Version={{.Tag}}'
      - -X 'auraspeed/cmd/root.Commit={{.Commit}}'
      - -X 'auraspeed/cmd/root.BuildTime={{.Date}}'
    binary: auraspeed
    mod_timestamp: '{{.CommitTimestamp}}'

archives:
  - format: tar.gz
    format_overrides:
      - goos: windows
        format: zip

checksum:
  name_template: 'checksums.txt'

snapshot:
  version_template: "{{.Tag}}-next"

changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
      - Merge pull request

release:
  github:
    owner: rkriad585
    name: auraspeed
